#spring:
#  jpa:
#    show-sql: true


spring:
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/spring"
#    username: "postgres"
#    password: "postgres"
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
